-- --------------------------------------------------------
-- Hôte:                         127.0.0.1
-- Version du serveur:           5.7.33 - MySQL Community Server (GPL)
-- SE du serveur:                Win64
-- HeidiSQL Version:             11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Listage de la structure de la base pour portfolio_laravel
CREATE DATABASE IF NOT EXISTS `portfolio_laravel` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `portfolio_laravel`;

-- Listage de la structure de la table portfolio_laravel. contacts
CREATE TABLE IF NOT EXISTS `contacts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `nom` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `message` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listage des données de la table portfolio_laravel.contacts : ~1 rows (environ)
/*!40000 ALTER TABLE `contacts` DISABLE KEYS */;
REPLACE INTO `contacts` (`id`, `created_at`, `updated_at`, `nom`, `email`, `message`) VALUES
	(1, '2021-10-13 08:46:59', '2021-10-13 08:46:59', 'zefdfgd', 'zefz@zef.zef', 'zefzefzefzefzef'),
	(2, '2021-10-13 08:49:16', '2021-10-13 08:49:16', 'zefdfgd', 'zefz@zef.zef', 'zefzefzefzefzef'),
	(3, '2021-10-13 08:54:21', '2021-10-13 08:54:21', 'ssdughskdhgsdoghih', 'lkjhlkjlksdfg@fgdfG.Dfg', 'eggklndfg dfg dfg dfg  d  dfg df g dfg dg dfg dfgd'),
	(4, '2021-10-13 09:08:54', '2021-10-13 09:08:54', 'sdsdfsdfsdf', 'zefzef@xn--fzef-uv7a.zef', 'zefzefze zefze fzefzefzefzefzef');
/*!40000 ALTER TABLE `contacts` ENABLE KEYS */;

-- Listage de la structure de la table portfolio_laravel. failed_jobs
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listage des données de la table portfolio_laravel.failed_jobs : ~0 rows (environ)
/*!40000 ALTER TABLE `failed_jobs` DISABLE KEYS */;
/*!40000 ALTER TABLE `failed_jobs` ENABLE KEYS */;

-- Listage de la structure de la table portfolio_laravel. migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listage des données de la table portfolio_laravel.migrations : ~6 rows (environ)
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
REPLACE INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2014_10_12_000000_create_users_table', 1),
	(2, '2014_10_12_100000_create_password_resets_table', 1),
	(3, '2019_08_19_000000_create_failed_jobs_table', 1),
	(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
	(5, '2021_10_12_084504_create_projects_table', 1),
	(6, '2021_10_13_082122_create_contacts_table', 1);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;

-- Listage de la structure de la table portfolio_laravel. password_resets
CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listage des données de la table portfolio_laravel.password_resets : ~0 rows (environ)
/*!40000 ALTER TABLE `password_resets` DISABLE KEYS */;
/*!40000 ALTER TABLE `password_resets` ENABLE KEYS */;

-- Listage de la structure de la table portfolio_laravel. personal_access_tokens
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listage des données de la table portfolio_laravel.personal_access_tokens : ~0 rows (environ)
/*!40000 ALTER TABLE `personal_access_tokens` DISABLE KEYS */;
/*!40000 ALTER TABLE `personal_access_tokens` ENABLE KEYS */;

-- Listage de la structure de la table portfolio_laravel. projects
CREATE TABLE IF NOT EXISTS `projects` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `date` date NOT NULL,
  `thumbnail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `meta_description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `meta_keywords` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `project_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listage des données de la table portfolio_laravel.projects : ~10 rows (environ)
/*!40000 ALTER TABLE `projects` DISABLE KEYS */;
REPLACE INTO `projects` (`id`, `name`, `date`, `thumbnail`, `description`, `excerpt`, `meta_description`, `meta_keywords`, `project_url`, `created_at`, `updated_at`) VALUES
	(1, 'Amet hic laudantium possimus qui molestiae.', '1970-02-14', '/storage/téléchargement1.jpeg', 'Architecto omnis rerum iste necessitatibus. Libero eos voluptatum praesentium qui est. Unde dolor veniam quia sed molestias.\n\nConsequatur ut repellat enim non. Corrupti minima quidem in quo nostrum quidem voluptatem. Illo totam aut repudiandae sed totam officia nemo. Voluptas est soluta sed voluptates error necessitatibus.\n\nRem est rerum labore est ipsa vel. Quasi blanditiis laborum id sed. Voluptatum est ea voluptates eius omnis natus.\n\nUt eos eos culpa. Autem tenetur illo vel ea dolore suscipit rerum. Eum itaque nulla molestias aut nostrum vitae. Qui voluptatem architecto inventore perspiciatis cupiditate doloremque enim.\n\nMaxime laudantium aut aut quam odio. Nesciunt ut at magnam sed eum. Praesentium dignissimos aut dolorem velit. Voluptatem similique incidunt eligendi deleniti quam.\n\nQuo inventore expedita dicta sequi qui voluptates. Natus qui labore at ut. Suscipit nostrum minus aut voluptas. Earum et at dolorum animi sint illo beatae sint.\n\nIpsa amet placeat sequi ipsa sequi dolore. Sequi est aspernatur hic ut temporibus et. Eligendi ex sit voluptas id cumque delectus et.\n\nSint expedita laboriosam id voluptatem necessitatibus. Ut sit voluptas sint accusamus. Molestiae dolor perferendis harum aliquam nemo et. Eos nihil debitis qui nam.', 'Voluptas enim pariatur vel nulla voluptates eum beatae. Aut est enim quaerat eum omnis. Et quis voluptatibus voluptatum quasi in dolores qui. Natus animi quo qui autem eaque. Qui reprehenderit nemo soluta sit accusantium.', 'Esse voluptatem eos cumque qui placeat.', 'laborum,modi,ipsum', NULL, '2021-10-13 08:41:16', '2021-10-13 08:41:16'),
	(2, 'Temporibus voluptatum distinctio harum.', '1998-11-12', '/storage/téléchargement2.jpeg', 'Consectetur a voluptatem sequi accusantium aut. Consequuntur consequatur nobis unde quas distinctio. Cumque error nobis quae sit qui quaerat.\n\nAut quia occaecati eveniet placeat aspernatur ut deleniti. Beatae commodi blanditiis qui et tempora cupiditate. Eum iste autem qui ipsum est corporis eum.\n\nQuos sint facere accusamus quia. Cumque aut eveniet rerum minus. Facere ipsam repellat accusantium quia autem. Blanditiis soluta ea vitae quod eum.\n\nFacilis qui quis ratione fugiat dignissimos. Magnam voluptatem nihil veniam at optio. Sit pariatur repellendus placeat quisquam hic aut. Iste eveniet deleniti est sit.\n\nUllam harum voluptas minima saepe necessitatibus deleniti magni. Et tenetur dolores reiciendis tenetur rem incidunt. Nihil officiis ea voluptatem excepturi. Ex aliquam cupiditate libero ut facilis saepe illo.\n\nEnim voluptatem quas modi. Unde officia nesciunt possimus ut ipsa ut dolor. Voluptates id quam omnis eius. Sit cumque quae unde.\n\nCumque architecto cum tempore et rerum occaecati. Aut iusto et non quia voluptatum aliquid. Animi est exercitationem odit veniam officiis sed numquam.\n\nInventore voluptas ut perspiciatis impedit quam quaerat. Distinctio explicabo quaerat omnis neque illum voluptas id. Architecto ipsum labore ipsa magnam officiis quia. Nostrum commodi nobis quod et itaque necessitatibus sit eos.', 'Eveniet nemo et aut amet ut doloremque quasi. Maxime eum itaque tempora iste laudantium voluptas qui. In aut corrupti praesentium quisquam ad. Impedit explicabo et rerum dolores voluptatem.', 'Ad sit expedita soluta debitis amet quibusdam sunt fugit.', 'sapiente,quas,ex', NULL, '2021-10-13 08:41:16', '2021-10-13 08:41:16'),
	(3, 'Perferendis quia et.', '1970-05-31', '/storage/téléchargement3.jpeg', 'Et sint dignissimos ut sint nemo sint. Accusantium sunt quo nobis aut facere tempore. Sapiente deserunt accusantium temporibus. Nostrum aut suscipit dolor eum iusto.\n\nVeritatis ullam odit enim deleniti quae neque aut. Suscipit ea ea magnam quaerat. Dolor quo nam aut aut illo culpa asperiores. Dolor a voluptatibus quia omnis quos.\n\nAnimi eligendi optio mollitia. Nostrum atque amet et libero. Ea quibusdam dolores autem iste ratione. Aperiam provident culpa in beatae eum et.\n\nSequi aut molestiae consequatur alias qui sit. Tenetur aut quae est reiciendis quo. Ut similique minima voluptatem dolorem qui et a. Adipisci consequatur et totam asperiores tempora saepe atque.\n\nExplicabo aspernatur nostrum provident nobis voluptas. Similique aut et corporis alias dolor. Consequatur quo voluptatem ullam.\n\nVoluptas et occaecati eligendi debitis atque. Odio fuga ullam omnis atque laboriosam. Et quaerat et corporis exercitationem. Tempore hic atque quia commodi magnam nihil qui quia.\n\nTempore amet non amet quia voluptas voluptatibus. Dolorem quis et iure aliquam et. Eveniet incidunt ut sit ullam est vitae est. Officiis suscipit ipsa nemo est sint.\n\nQuasi sequi asperiores minima neque aliquid natus ut assumenda. Qui sit nemo deleniti maxime eligendi molestias veniam nemo. Aut nisi quam rerum corrupti deserunt.', 'Voluptas recusandae rerum occaecati molestias in et aut. Rerum sint et fugit expedita optio. Nihil recusandae voluptatem non perferendis esse a dolorem. Laboriosam eum error id ullam. Repellendus officiis quo quas impedit.', 'Facere dolorem porro voluptates accusantium.', 'perspiciatis,dolor,reprehenderit', NULL, '2021-10-13 08:41:16', '2021-10-13 08:41:16'),
	(4, 'Qui molestiae dolores non nam.', '1992-05-20', '/storage/téléchargement1.jpeg', 'Cupiditate consequatur exercitationem asperiores officiis dolorum. Nostrum accusantium qui veniam voluptas exercitationem. Rerum quasi nobis laboriosam enim. At soluta aut incidunt debitis sint. Eum odit nulla nihil totam iusto veritatis.\n\nDelectus et ut sequi nulla quibusdam rerum possimus. Alias eum inventore eligendi est sed enim iure. Incidunt dolores suscipit at et minima fuga in velit. Aperiam nostrum rem dolore consequuntur. Rem omnis molestiae omnis sapiente eligendi rerum.\n\nSed enim pariatur hic aut est accusantium non. Natus blanditiis corrupti nemo. Voluptas minus et aut eveniet architecto. Saepe ipsum fugiat labore sequi. Laborum sint ipsam numquam omnis reprehenderit tempore.\n\nEius omnis ut libero et. A reiciendis nihil laborum rerum necessitatibus ab labore. Rerum cumque omnis esse vel rerum asperiores.\n\nRerum sit corporis explicabo ut autem sed velit. Et aut incidunt laudantium voluptates. Quis et voluptates aspernatur unde. Consequuntur esse et et placeat eos et.\n\nQuia consectetur hic est perspiciatis. Error inventore necessitatibus non officia sed doloribus quam. Suscipit fugit et non omnis dolore.\n\nQuidem ut sint non quasi eos. Sunt expedita id aut. Dolor quas minima molestiae accusamus. Harum beatae ut rerum repellendus alias dignissimos.\n\nUt a rerum repudiandae nulla repudiandae ratione tenetur. Occaecati voluptatem rerum iste modi. Consectetur minima ut aliquam quas dolorem quod. Excepturi cumque molestiae maiores sit. Quia maxime enim est inventore suscipit animi voluptate.', 'Tempore nesciunt aspernatur similique dolor a laudantium numquam. Est neque dolore quo temporibus accusamus voluptatem. Est placeat quia ut eveniet.', 'Quos dolor sed quidem voluptatum nesciunt maiores.', 'et,sit,quisquam', NULL, '2021-10-13 08:41:16', '2021-10-13 08:41:16'),
	(5, 'Illum nemo soluta.', '1996-08-13', '/storage/téléchargement2.jpeg', 'Voluptatem quam et qui omnis omnis corporis rem aspernatur. Consectetur nisi vel cum et est amet aut qui.\n\nQui eum labore laudantium rerum voluptas. Optio qui amet labore eos. Vero consequuntur beatae atque iusto quia voluptates. Ratione et voluptatem accusamus aut deleniti quia minima.\n\nEius omnis sit aut dolores fugit aut incidunt. Non voluptas vel quas harum dolores est. Consequuntur sit cumque temporibus velit nihil laudantium.\n\nEos sed et expedita. Suscipit officiis explicabo pariatur. Eos dicta facilis alias rem temporibus aliquid velit. Minus et dignissimos totam a voluptas quod. Quis deserunt qui qui corporis deleniti dolorem dolorum sunt.\n\nNemo dolor ad quo voluptatem cum. Sit enim sed commodi iste dolore sit. Totam beatae eveniet deleniti a et est saepe. Expedita eos quia qui quos ducimus ratione ut suscipit.\n\nDoloremque magnam alias rem modi. Hic aut magnam optio et nihil natus. Accusantium molestias sed vero provident. Pariatur perspiciatis rem molestiae nihil et eius quod.\n\nEt veniam commodi architecto. Nemo corporis maiores accusantium necessitatibus laboriosam explicabo at atque. Quasi rerum sunt omnis autem laudantium. Fugiat nostrum nesciunt voluptatem officia et et optio.\n\nVoluptates rerum ducimus consequatur similique rem. Laboriosam distinctio quas enim sapiente beatae facere quo. Ab maiores est qui. Explicabo ea blanditiis voluptatum culpa at rerum assumenda.', 'Tempora vel et est veritatis voluptatum quibusdam et. Consequatur qui soluta doloribus quidem labore quibusdam. Amet et veritatis quo eligendi cumque.', 'Earum ratione aperiam velit nisi reprehenderit qui aut.', 'non,non,fugiat', NULL, '2021-10-13 08:41:16', '2021-10-13 08:41:16'),
	(6, 'Sunt quia modi aperiam.', '1994-09-01', '/storage/téléchargement3.jpeg', 'Voluptatibus voluptas numquam asperiores. Velit cum adipisci omnis ut mollitia. Ducimus sed nesciunt omnis qui eum dolorum. Quia praesentium qui dolores dolorem alias deleniti.\n\nAssumenda et omnis quis ullam dicta quod. Aspernatur consequatur quia rerum laboriosam doloremque laborum quaerat quos. Omnis sed officia quia non.\n\nAccusamus molestias consectetur aut porro dolor placeat. Dolorem voluptas voluptas officiis. Ut deleniti quos omnis qui. Id reprehenderit voluptates quos.\n\nVoluptas delectus animi ut aliquid dolorem quia voluptatum. Velit et inventore veritatis omnis rerum incidunt minus. Voluptatibus recusandae ipsum ea quia rerum neque eum.\n\nRerum esse saepe dolores illum est. Voluptas enim a qui. Porro iusto excepturi odio laboriosam unde et illo. A debitis id nemo cum iusto iste. Alias ut non consequatur alias.\n\nUllam voluptas illum voluptatem non sed. Voluptatem vero officia officiis. Delectus quaerat et totam qui dicta omnis. Eligendi in sit animi suscipit laudantium.\n\nQui officiis velit natus est quaerat magnam ullam. Enim exercitationem commodi quas magnam. Alias iusto quos nesciunt modi provident unde. A et qui odit aut sit non.\n\nExercitationem rerum sapiente dolore magnam nam omnis qui. Assumenda eaque eius quibusdam qui in velit ratione. Quasi ut consequatur minima esse possimus facilis qui quasi.', 'Culpa at et ipsa ullam est. Quo velit repellendus deleniti necessitatibus. Quis debitis rem pariatur aliquid.', 'Rerum dicta vero officiis libero laborum.', 'deserunt,fugit,aliquid', NULL, '2021-10-13 08:41:16', '2021-10-13 08:41:16'),
	(7, 'Doloribus dolor iusto.', '2004-12-27', '/storage/téléchargement1.jpeg', 'Porro velit quia qui id aliquid laboriosam. Illo quam minus accusantium delectus qui eum ex. Nobis nostrum voluptatem sit.\n\nConsequatur quam quia repellat facilis dolore cumque et. Quia necessitatibus sed qui et voluptatibus. Delectus cupiditate officiis accusantium itaque ex est. Eligendi dolorem harum similique similique placeat qui est.\n\nItaque libero maiores aut odit qui ducimus est. Quos culpa saepe enim at porro. Molestiae consectetur quis magnam natus consequatur explicabo dolorem.\n\nEveniet nisi reiciendis accusamus iste minus dolorem facilis dolore. Amet sed voluptates aliquam earum minima. Laborum voluptates magni voluptatum sunt ea cumque.\n\nConsequatur molestias aliquid quis sunt aperiam quos. Aliquid dolorem similique quo error. Sed ipsum ut distinctio eius ut vero. Ducimus dolorum est aliquid cum placeat. Animi soluta veritatis ad amet.\n\nVoluptate aspernatur libero est voluptate error aliquam sequi. Fugit quae eum est rem. Ab saepe sit qui corporis dicta totam consectetur. Enim veritatis consequuntur explicabo odit.\n\nNon eveniet eos ad exercitationem. Numquam eos cum qui aliquam perspiciatis nesciunt nemo. Qui sapiente a architecto voluptas eaque quaerat.\n\nNon quisquam unde officia quia. Neque sunt sint in autem occaecati qui facilis. Dolores maiores quia animi quibusdam.', 'Est labore eos est dolorem animi soluta est. Omnis itaque ut aut itaque harum incidunt ab ut. Velit architecto officiis quae reprehenderit. Omnis nihil cum totam corporis molestiae omnis.', 'Id iure iure dignissimos rerum magni et.', 'et,expedita,pariatur', NULL, '2021-10-13 08:41:16', '2021-10-13 08:41:16'),
	(8, 'Soluta ducimus vero est reprehenderit.', '1976-11-16', '/storage/téléchargement2.jpeg', 'Ab quo repellendus aliquid nemo nobis. Possimus odio autem dolorem voluptas qui vel beatae. Veritatis nihil doloribus iusto totam fugiat iusto quo. Placeat est tempore modi et vel amet sint quas. Non ab amet velit nam ea.\n\nQui omnis aspernatur eos illum nam itaque aliquam. Ut facere ea magni consectetur et aut aperiam exercitationem. Est ab eius et ea omnis aut id. Ratione qui sunt laborum accusamus illo quas dolorum.\n\nSit dolores amet repellat et omnis est. Nostrum optio adipisci quo quia. Suscipit natus ut suscipit architecto.\n\nEligendi a esse ut harum officia. Ipsam rerum porro ipsa et fuga neque reiciendis. Voluptas culpa earum quibusdam illo explicabo.\n\nLabore corrupti qui dolorem sint similique cumque placeat. Pariatur quos odio et cum recusandae. Harum atque ut culpa est eius quis.\n\nHic velit qui debitis placeat. Ullam dolores delectus explicabo dolores veritatis autem.\n\nExplicabo vero asperiores quo quibusdam quia molestiae quis. Velit animi vel eligendi delectus dolorum non nulla. Et rerum corporis quidem repellendus blanditiis eveniet.\n\nEum nisi maxime repellendus eligendi consequuntur delectus. Dignissimos id soluta tempora et. Voluptatibus suscipit inventore qui dolor.', 'Est eos impedit laborum cumque sunt. Totam deleniti ut expedita accusantium id qui occaecati placeat. Consequatur aperiam ipsam veritatis. Amet ut et iste mollitia facere eligendi pariatur.', 'Laudantium in dolores qui at consequatur ex architecto.', 'et,tempora,ipsum', NULL, '2021-10-13 08:41:16', '2021-10-13 08:41:16'),
	(9, 'Autem facilis consequatur voluptate aut veniam.', '2013-03-02', '/storage/téléchargement3.jpeg', 'Aut officia consequuntur non voluptatum. Nihil quas fuga placeat eveniet. Fugiat corporis et occaecati laboriosam delectus reprehenderit rem. Sequi ut asperiores omnis quam nihil. Inventore voluptatem quia quo dolore animi.\n\nProvident architecto aut officiis unde. Voluptas voluptas expedita ut qui dolor. Repellendus sed laudantium consequatur consequatur sunt eum. Enim voluptatem veritatis ut provident fugit omnis.\n\nOccaecati aspernatur illum exercitationem doloribus. Nihil perspiciatis ipsam vitae dolore at. Pariatur a qui quibusdam eos. Quo voluptatem laborum dicta nihil quis voluptas.\n\nAperiam commodi voluptatem at numquam et et. Dolorum dignissimos commodi explicabo sunt. Et explicabo harum perspiciatis mollitia et ut ipsam velit. Molestiae illum qui voluptates in. Vel enim velit molestias qui.\n\nVeniam autem nobis consequatur voluptatem. Praesentium qui itaque eligendi quisquam laudantium atque suscipit dolor. Impedit nihil velit eum minus tempora quia voluptates sequi.\n\nEst ratione nesciunt enim ipsam. Voluptas molestiae ipsam facilis est. Qui cumque aut illo. Inventore officiis quas minus ipsam voluptatibus sed quos.\n\nNobis voluptas quis hic molestiae illum. Molestias id sint reprehenderit eos. Facilis quia molestiae enim illum consequatur repellendus ad. Unde perspiciatis provident amet tempore debitis quasi quasi tempore. Illum quia corporis non exercitationem quisquam impedit.\n\nAdipisci fugiat velit beatae ipsam et dicta iure est. Optio ipsa ut qui voluptate. Molestias molestias maiores aut et quibusdam minima sed. Quo voluptate natus tenetur rerum itaque iure dignissimos. Quia itaque voluptatem nostrum ut laborum commodi cum.', 'Voluptas natus excepturi soluta quas. Pariatur rerum consequatur optio ut amet et officia. Ex placeat qui placeat est. Quam voluptate repellendus tempore voluptas et corrupti eveniet. Beatae sunt nam optio numquam repellendus quis.', 'Nesciunt dolor cupiditate ullam est earum.', 'veritatis,perspiciatis,placeat', NULL, '2021-10-13 08:41:16', '2021-10-13 08:41:16'),
	(10, 'Fuga quis nemo.', '2018-05-09', '/storage/téléchargement1.jpeg', 'Asperiores facere saepe voluptatum. Minima quo sint eaque molestiae sit sunt. Occaecati occaecati qui earum numquam. Aspernatur totam cupiditate dignissimos architecto qui sint quia.\n\nDolores est et vel. Ipsa laudantium voluptate quam odit ea nemo. Mollitia et quia totam. Et quos natus amet voluptate quia placeat repellat.\n\nEa odio ut natus laborum quis. Quae nemo iste praesentium aut. Praesentium id sunt et et beatae voluptas nostrum. Similique vel dignissimos fuga eaque voluptas.\n\nMagni iste qui eveniet illo voluptatem veritatis voluptates. Quaerat impedit nostrum quod provident. Nemo dicta dolores sed officia nostrum similique a adipisci.\n\nEligendi eius ex consectetur fugiat ut. Esse et quo voluptatem odio. Harum deleniti est blanditiis voluptatem doloremque. Et sit doloribus suscipit ducimus iure.\n\nQuia amet quos nihil enim quaerat sed deleniti ut. Ut molestias placeat inventore placeat ut aperiam. Dolor itaque in non quis similique.\n\nCorrupti quos iusto incidunt veritatis. Quis illum nisi voluptatum odit. Qui molestias ut vitae sit ea. Perferendis dolor asperiores necessitatibus eum consequuntur. Distinctio sed qui dolor officiis ut.\n\nFacilis velit magni qui est. Quam et nisi officia id et. Tempore corrupti aut quibusdam illo ut. Omnis ut accusantium eos necessitatibus adipisci facere necessitatibus.', 'Facere voluptatem quis voluptas numquam dignissimos et eum. Non repellendus eos beatae at consequatur et. Rerum et quod qui qui. Soluta tempore laudantium similique aut magnam recusandae. Placeat natus vel sint tempora maiores error quia.', 'Aut enim excepturi et omnis.', 'quia,sed,possimus', NULL, '2021-10-13 08:41:16', '2021-10-13 08:41:16'),
	(11, 'Adipisci mollitia itaque temporibus.', '2001-10-19', '/storage/téléchargement2.jpeg', 'Quam aliquam qui neque et. Ducimus facere sed voluptatem voluptatibus harum. Est iste odit quam ut placeat reprehenderit nostrum. Fugiat ut fugit deserunt ab nisi id aperiam et.\n\nAb quia quia distinctio sapiente nesciunt saepe id. Iure fugiat voluptas asperiores aperiam. Consequuntur totam quia eum. Odit eaque inventore at est quia distinctio beatae. Necessitatibus illo consequatur quibusdam quis voluptatem.\n\nHic voluptates est similique facilis. Odit recusandae accusantium excepturi necessitatibus maiores occaecati est tempore. Est illum et alias quia. Consequatur exercitationem et aut sint. Eos quisquam voluptatem qui iusto eos.\n\nExpedita fugiat et occaecati ratione tempore est quisquam. Ad amet eaque vel eos. Voluptatem sed est et voluptatem eos assumenda magni.\n\nEst sequi incidunt odio doloribus et dignissimos. Iste est pariatur iure. Necessitatibus autem earum ab ipsum velit velit.\n\nDistinctio illum quia minima voluptate. Occaecati tenetur fuga nostrum. Cumque iusto occaecati ut nisi optio consectetur. Et aperiam dignissimos ut.\n\nProvident accusamus qui porro velit omnis laboriosam id ea. Omnis officia nihil quis sapiente accusamus consequatur eum error. Ut explicabo tempore dolorem esse harum natus.\n\nTenetur voluptas blanditiis dignissimos repellendus minus voluptatibus. Dolores accusantium recusandae nisi qui. Voluptates necessitatibus ea ut.', 'Fugit placeat hic est provident. Quibusdam accusamus velit necessitatibus unde ipsam nihil ducimus. Sint officia necessitatibus et dolores qui sit rem vitae. Ea nulla quisquam voluptatibus deleniti dolorum. Ad eum vel quia ducimus tempora eum. Reprehenderit facere corrupti quia dignissimos dolorem quam laborum.', 'Quasi hic sint at sit id voluptatem.', 'blanditiis,magnam,doloribus', NULL, '2021-10-13 08:51:50', '2021-10-13 08:51:50'),
	(12, 'Voluptatem est quas nobis.', '1977-11-30', '/storage/téléchargement3.jpeg', 'Sunt odio et eum natus. Exercitationem consectetur harum expedita et quis aut ea. Occaecati sunt sed placeat enim quasi enim repellat.\n\nIpsum qui aut sint explicabo velit nemo sit. Officia aut adipisci eos ducimus quia quaerat sit natus. Omnis quia culpa quas quis explicabo beatae vitae.\n\nNobis corporis pariatur rerum ipsam quis est dolorem. Sit eius quia et et corrupti. Officia voluptate facilis quia consequuntur possimus.\n\nConsequatur hic sed beatae sit officiis dolores veritatis. Possimus et corrupti sed at ex et. Possimus doloremque dignissimos laboriosam et eos. Aut eligendi in sequi pariatur provident quidem iusto sit.\n\nDolores ut ex dicta qui voluptatem perferendis commodi sit. Corrupti soluta officia rem nisi commodi quis accusantium. Porro dolor aliquam ad tenetur.\n\nPerspiciatis esse voluptas sed nostrum a vel perspiciatis. Sequi omnis nam consequatur voluptatem rerum sed aut.\n\nDolor dolor cum maiores officia. Assumenda doloremque maiores nihil deserunt vel corrupti est. Est autem excepturi laborum quod molestiae. Laudantium cum ipsam perferendis qui deleniti cumque perspiciatis.\n\nEum perspiciatis molestiae inventore consectetur sapiente ut id. Enim et facilis iste. Deleniti laudantium sunt facilis nemo.', 'Qui molestiae praesentium autem cum. Fuga cumque quia dolore molestias. Dolor dolores optio tempora. Aliquam aut id id odio rerum aperiam est.', 'Nobis itaque aut autem adipisci voluptatem fuga.', 'voluptas,dolor,occaecati', NULL, '2021-10-13 08:51:50', '2021-10-13 08:51:50'),
	(13, 'Fugit aut quaerat beatae aut.', '2015-01-31', '/storage/téléchargement1.jpeg', 'Totam vel assumenda numquam. Et inventore voluptates accusamus sit ut a. Modi natus eos alias itaque. Aut doloremque similique ad enim.\n\nFuga repudiandae ea et asperiores voluptatem. Sunt iste consequuntur tenetur et. Quia alias repellat unde porro.\n\nVelit nihil quaerat iusto perferendis aspernatur eum. Itaque voluptas beatae in eveniet. Quas dolorem similique sapiente repellat veniam. Cupiditate neque iure eos et neque quasi.\n\nBlanditiis aspernatur ad blanditiis fugit omnis nihil optio. Animi fuga dolor et aliquam qui quos. Molestiae sit minus et. Earum qui voluptates doloremque quia quia reprehenderit. Tempore eveniet aliquam sunt quia saepe.\n\nPerspiciatis temporibus harum vero fuga odit a iusto. Voluptatem perferendis et minus eaque labore delectus doloremque. Consequatur magnam et facere omnis cupiditate itaque dolores error. Ut veritatis incidunt laudantium enim eos voluptatem neque nulla. Et maxime eos quaerat corrupti sit nostrum sint.\n\nSunt est laudantium sed quos molestias. Quae quam cupiditate dolores est. Necessitatibus et dolore quia.\n\nConsequatur illo est itaque beatae maxime. Architecto temporibus quam sed velit. Totam fugiat id non voluptas magni dolorem. Quaerat illum earum deleniti voluptatum magnam ut ipsum.\n\nAliquid voluptatem ad reprehenderit non unde consequuntur error delectus. Et sunt atque eos rem unde. Eos cum nisi eligendi cum iure officia minus. Odio vero tempora quia esse.', 'Voluptas quas debitis autem iste et. Velit consequatur repellat maxime illum. Aut fuga laborum deleniti est nihil vitae. Molestiae dolores qui voluptatem sed voluptatem sequi. Illum fugit ut nihil.', 'Sint at quia aliquam facilis doloremque sint error.', 'qui,molestiae,sed', NULL, '2021-10-13 08:51:50', '2021-10-13 08:51:50'),
	(14, 'Magnam debitis harum incidunt.', '2009-06-02', '/storage/téléchargement2.jpeg', 'Neque repellat sunt quia laborum fuga eum ipsam repellendus. Consectetur expedita repellat impedit quia et. Nihil quia molestias cupiditate exercitationem labore qui mollitia.\n\nIpsa suscipit voluptatibus vitae accusamus minima. Dolorem magni adipisci nesciunt nihil. Provident atque at voluptas consequatur. Delectus molestias commodi atque cum libero quam.\n\nDignissimos ipsam vel aperiam ullam adipisci rerum nostrum et. Animi amet placeat quaerat iste. Fugiat et odit repudiandae fuga repellendus. Nihil sit illum dignissimos eligendi magnam.\n\nAb laborum quibusdam quia autem animi veritatis. Minima dignissimos illo aut consequatur architecto quia dolor. Id et amet qui atque repudiandae dolorum dolorum.\n\nModi qui molestias inventore eum voluptatum temporibus enim omnis. Ut ipsum quis libero dolor nulla. Debitis dolor unde odio necessitatibus non quia.\n\nQuae atque perspiciatis sed numquam ipsam. Tempore et placeat facere repudiandae odio est repudiandae. Adipisci fugiat ut harum aut explicabo minus consequatur nemo. Explicabo autem in laudantium perferendis qui doloribus omnis laboriosam.\n\nIpsam nulla corrupti ipsum id. Voluptas totam repellat assumenda provident totam. Aut et laudantium voluptatem illum sunt dolorum velit. Harum harum dolorum sed explicabo illo et. Quisquam voluptates voluptate sed voluptatem aut quod.\n\nLibero adipisci maxime sunt velit id ipsa consectetur at. Nisi quod perferendis ratione id. Atque occaecati qui itaque unde repellendus porro. Veniam minima nulla voluptatem.', 'Aliquam consequuntur sint asperiores harum. Atque id molestiae aut fugit. Deserunt dolorem nam recusandae totam at magni. Consectetur unde a iste aliquid.', 'Assumenda sint officia eaque provident.', 'vero,nihil,commodi', NULL, '2021-10-13 08:51:50', '2021-10-13 08:51:50'),
	(15, 'Aut assumenda delectus accusamus.', '1975-09-27', '/storage/téléchargement3.jpeg', 'Impedit unde eligendi ipsa facilis error incidunt sapiente architecto. In non cupiditate incidunt.\n\nAut optio expedita ab dolores harum. Et voluptas id molestias in voluptatibus. Molestias quos et sed id facere incidunt illo. Ea impedit est esse omnis dolores cupiditate.\n\nArchitecto rerum id nobis quisquam minima ab expedita quibusdam. Sunt excepturi voluptatem et unde eveniet sed nemo. Alias cum atque corporis ea aut tempora. Corporis qui laudantium ut. Labore reprehenderit voluptas nemo aut atque.\n\nNisi aliquid quia nulla. Delectus necessitatibus quia vel omnis non. Sit quae eveniet voluptatem cumque.\n\nUt non quidem praesentium esse. Molestiae nihil numquam expedita magni vel aut voluptates. Eius non sunt voluptas.\n\nOmnis beatae in in et. Doloribus incidunt molestiae quo velit facere. Est amet eius aperiam vel excepturi consequuntur. Id amet est non illo.\n\nSit repudiandae similique aut et. Aut reprehenderit ad quae sunt earum et. Eos et omnis consectetur.\n\nQuae assumenda in et quo adipisci libero qui. Illo earum deleniti dolorem delectus. Quis quis veniam quisquam. Aut reprehenderit ut aut officia at possimus.', 'Exercitationem animi quod excepturi veritatis. Sint temporibus voluptatem rem earum et dolorem eligendi laudantium. Ut facere esse reprehenderit natus error molestiae exercitationem. Ullam necessitatibus sed asperiores est distinctio doloremque ducimus eos. Consequatur ut magni ipsa eos autem quam sunt.', 'Iure explicabo aliquam qui ut repellat.', 'et,aliquid,voluptate', NULL, '2021-10-13 08:51:50', '2021-10-13 08:51:50'),
	(16, 'Eum fugiat vel dolores beatae.', '1971-04-14', '/storage/téléchargement1.jpeg', 'Quae distinctio molestiae incidunt quia velit animi. Dolorum tempore aut vitae odio qui quis error nam. Nisi culpa optio id sint adipisci. Occaecati ut tempore nam facere.\n\nEst et iste magnam praesentium neque temporibus. Occaecati dignissimos corporis repellat sit. Et corrupti harum neque sint voluptatum temporibus dolores. Iusto iusto ut neque illum repellat dolores.\n\nSoluta deleniti ab omnis non repudiandae aut numquam pariatur. Voluptatem qui perspiciatis et assumenda magni. Provident nostrum est et dignissimos earum quidem unde. Et molestias nesciunt voluptas officiis provident.\n\nQuia asperiores nam impedit voluptate sint ut aperiam consectetur. Impedit qui est repellendus veritatis.\n\nMinima repellendus officiis officia voluptas. Ducimus dignissimos odio quae eos. Facere illo explicabo voluptatem illo magni.\n\nEst dolores neque aliquam aliquam ab possimus. Autem tempore quaerat est et placeat. Perspiciatis delectus temporibus quo minus et sed et.\n\nImpedit explicabo praesentium placeat deleniti tempora. Voluptatem ea soluta cum inventore hic nihil delectus commodi. Incidunt officiis soluta reprehenderit.\n\nOmnis est sed quae quae autem illum impedit. Iusto eligendi consequatur harum maiores labore magni minus occaecati. Et aut nulla vitae laudantium ex eum magni.', 'Molestias qui omnis dolores temporibus possimus nesciunt. Vel reiciendis omnis pariatur qui ea. Rem asperiores incidunt quia velit consequatur. Nihil laudantium assumenda in cum non nihil in laboriosam. Officia dolorem repudiandae corporis. Maiores vel adipisci eaque qui delectus.', 'Error rerum consequatur in omnis ut.', 'natus,maxime,officiis', NULL, '2021-10-13 08:51:50', '2021-10-13 08:51:50'),
	(17, 'Et excepturi incidunt id id.', '1996-07-22', '/storage/téléchargement2.jpeg', 'Illo ipsam qui velit esse et iste. Qui doloribus vel dicta. Aut consequatur ratione eos enim debitis nihil magni. Rerum neque laboriosam id.\n\nUllam magnam fuga atque quis quisquam. Eligendi modi ad rerum ad minima. Iusto ut neque omnis quo qui praesentium aliquid. Maxime sint occaecati et sequi non.\n\nPlaceat consequatur facere voluptatem aliquam aut. Rerum labore vel voluptatem velit at nihil.\n\nAliquam itaque autem sapiente perspiciatis. Perferendis omnis est et vero. Laborum non dolorem sequi ea laudantium aut maxime eos. Consequatur perspiciatis dolore voluptatum totam doloremque. Eligendi aspernatur voluptates molestias sit quia quos esse quasi.\n\nPariatur in dolor doloremque ut. Modi voluptatibus et odio quo. Harum sunt cum velit et totam soluta consequatur.\n\nEa impedit veniam quae deserunt aliquid et quas. Vitae quo vel aut vero officia. Ipsum eveniet nulla porro temporibus voluptatem accusantium aut. Sunt voluptatibus labore quia omnis.\n\nEum suscipit nam beatae nisi ut velit earum. Omnis laudantium ipsa atque veritatis rerum aliquam officiis consequatur. Sunt odit veniam voluptatem. Laborum aut nesciunt voluptatem iste fugit odit.\n\nAssumenda odit eligendi aliquam voluptatem. Quis eos ipsum ipsa. Hic unde et quod vel necessitatibus ad. Dolorem molestiae sapiente temporibus harum.', 'Adipisci sequi nam non iste tempore. Ut ut unde ratione sequi. Illo eum non asperiores ut dolores sint beatae omnis.', 'Consequatur sed est magnam enim aut illo.', 'qui,qui,rerum', NULL, '2021-10-13 08:51:50', '2021-10-13 08:51:50'),
	(18, 'Nihil praesentium fugiat et.', '2004-09-14', '/storage/téléchargement3.jpeg', 'Dolorem perferendis amet enim pariatur consectetur. Molestiae aliquam omnis ex dolorum voluptas. Laborum dicta tempora beatae ipsum hic ea.\n\nPlaceat rerum nam et id voluptas. Aut explicabo tempora eligendi rerum. Ut dolorem id et asperiores voluptas dolorem. Rerum delectus voluptatibus optio.\n\nTotam quo inventore illum corrupti et omnis libero tempora. Ex cupiditate animi illum quia totam ut. Vel maiores nesciunt molestiae fuga reprehenderit ea voluptatem culpa. Dolores enim delectus dolor earum qui qui reiciendis impedit.\n\nPorro quisquam assumenda neque illo nostrum. Eaque aut impedit deleniti possimus. Similique doloremque quis esse qui.\n\nQuo harum id dolor error omnis. Saepe possimus porro blanditiis omnis inventore rerum. Accusamus dolorum velit ab atque voluptas. Et laudantium autem ab architecto vel consequatur quo.\n\nNisi et et consequatur necessitatibus sint. Labore optio deleniti maxime dolores tempora. Quam autem ea minima fuga aliquam ex. Non incidunt dicta in rerum ut.\n\nBeatae expedita omnis necessitatibus. Beatae laborum ex consequatur voluptates qui modi aut. Omnis aliquam ipsum aliquam voluptatem quisquam temporibus incidunt.\n\nEt ab voluptas facilis ullam velit exercitationem. Et laboriosam non sint. Fuga ipsum sed voluptatum atque omnis.', 'Aut nobis expedita autem consequuntur ut recusandae. Temporibus pariatur sed doloribus rerum et repellat. Nostrum accusamus dolores expedita dolor eos. Aut voluptas quo facilis necessitatibus ullam omnis reprehenderit ea. Ut id quam officia eos corrupti rerum magni. Quas reiciendis perferendis rerum omnis nam vel sint aspernatur.', 'Ad rerum consectetur modi error quia adipisci sit.', 'ut,sunt,aut', NULL, '2021-10-13 08:51:50', '2021-10-13 08:51:50'),
	(19, 'Consequatur exercitationem consequuntur quia repellendus.', '1993-07-04', '/storage/téléchargement1.jpeg', 'Nihil qui aut explicabo sint beatae omnis. Eveniet sint dolore placeat. Qui quia corrupti nam dolorem vel vel.\n\nPossimus velit earum quis officiis dolores. Minima laborum minima id eos odio sit. Deleniti autem sit fugit suscipit incidunt quibusdam. Dignissimos tempora officiis magnam perspiciatis amet ut.\n\nUt voluptatibus dolores consequatur ea odit. Omnis voluptas qui ipsa assumenda debitis suscipit ad. Voluptatibus dolor fugiat ut dolor perferendis. Aut dicta dignissimos voluptatem earum mollitia porro ex.\n\nEt omnis voluptatum itaque voluptatum facilis ad. Minus similique sit repudiandae consequatur aut corrupti. Quia ipsam dolorum nesciunt delectus.\n\nOptio perferendis ea aspernatur quo ut vitae reprehenderit. Cumque placeat saepe eos temporibus minus. Perferendis nesciunt et excepturi nam voluptatem non.\n\nLaborum iste nihil officia similique. Delectus laborum consectetur aut perspiciatis quia occaecati facilis.\n\nDolorem harum fugiat libero non voluptas pariatur. Consequatur et sunt eos voluptas iste. Tempora atque asperiores accusamus saepe alias fugit excepturi.\n\nDolor ea et a iste. Est voluptatem rerum molestiae aliquam molestias. Dicta quam ut rerum labore.', 'Blanditiis non suscipit est fuga. Aperiam distinctio dicta animi fuga corrupti eligendi. Excepturi aut non voluptatem omnis.', 'Qui omnis sapiente ex accusamus.', 'sed,in,occaecati', NULL, '2021-10-13 08:51:50', '2021-10-13 08:51:50'),
	(20, 'Et voluptas eius at veniam.', '1992-07-09', '/storage/téléchargement2.jpeg', 'Qui reprehenderit tenetur et id quae nihil sit. Reprehenderit vitae excepturi et sed cum est rerum. Ad id omnis quam debitis. Quisquam voluptatibus non expedita autem et.\n\nEt explicabo ut dicta temporibus qui. Autem ex et quo optio sunt corrupti. Fugiat voluptate ipsa enim minima molestiae quis quidem.\n\nDistinctio quo nihil id ipsum. Voluptatem in quos nostrum. Hic ut repudiandae ex id soluta.\n\nAlias et qui maxime eaque placeat labore quam. Ut debitis veniam quis quo voluptas. Et eius recusandae qui est libero. Deleniti est et et vel quod.\n\nMolestiae voluptatum et dolores explicabo veniam voluptatem consequatur. Ipsa odit veritatis consequatur quis quae. Hic ut asperiores aut blanditiis provident ratione. Officia voluptatem explicabo quia.\n\nMaiores sint aspernatur iure suscipit assumenda. Praesentium doloribus nihil porro quis. Sit nihil excepturi aut.\n\nBlanditiis sint sapiente sed aut. Iure molestiae necessitatibus rem accusantium ab aspernatur quos consequatur. Autem ex doloribus recusandae non.\n\nEt aut molestiae voluptas minus non ab deleniti. Ut nostrum quod saepe aut sit. Nihil cum incidunt ratione. Vel alias ullam corporis accusamus error porro similique.', 'Ea quasi molestiae ullam quidem. Id ut autem architecto sunt culpa non officia. Maxime dolorem natus accusamus doloremque nihil. Enim vero labore nam perspiciatis velit. Qui totam quam nulla qui voluptatibus. Sunt aut et exercitationem non atque doloribus.', 'Eveniet sed alias quo consequuntur dolorem.', 'magnam,possimus,aut', NULL, '2021-10-13 08:51:50', '2021-10-13 08:51:50'),
	(21, 'Amet doloribus sed.', '2019-03-06', '/storage/téléchargement3.jpeg', 'Nesciunt molestiae nesciunt odit laborum mollitia distinctio dolores. Eos quidem sequi ab aut dolorem consectetur est. Occaecati rerum eos dolor doloribus eaque eligendi ut.\n\nPariatur at nostrum unde et. Ullam nisi sed voluptates est esse distinctio voluptatem. Quis quo dolores sint in totam et rerum.\n\nVoluptate aut sapiente fugit tenetur corporis. Quaerat eveniet qui rerum quo laborum. Et facere recusandae est quos.\n\nSint id doloribus sit cum. Dolor sit beatae accusamus sint. Voluptas officia sint dolorum.\n\nQuibusdam voluptatem culpa quis facere. Tempora numquam tempore eos. Officia amet est in cupiditate rerum. Doloribus possimus dolores et nesciunt officiis.\n\nRepudiandae animi quod iusto saepe. Ipsa voluptas aut assumenda distinctio deleniti nisi.\n\nSint molestiae et dolorum architecto sequi. Dolores voluptatem itaque impedit. Voluptatum in et est voluptatem. Aliquid rerum aut minus id.\n\nRepellat amet alias dolor temporibus. Ut repellendus ad enim neque et doloribus.', 'Quia deleniti placeat sit voluptas velit eum atque. Id dolor omnis porro asperiores accusantium. Quia blanditiis eaque voluptas. Sunt nisi deleniti dolores repudiandae autem omnis rerum. Non enim in praesentium consequatur. Inventore architecto ullam saepe non vel repellat est.', 'Eius doloribus necessitatibus temporibus ut delectus dolor aut.', 'ratione,minus,exercitationem', NULL, '2021-10-13 08:51:52', '2021-10-13 08:51:52'),
	(22, 'Non fuga qui deserunt ut.', '2010-10-14', '/storage/téléchargement1.jpeg', 'Minus corrupti facere voluptas aperiam dicta nulla. Ducimus accusantium eum rerum aliquam quasi suscipit. Voluptate impedit possimus placeat tempore.\n\nSunt eos sunt voluptas incidunt doloribus commodi consequatur. Sunt voluptatem qui reiciendis ad qui velit. Vel eveniet magni similique ut odit.\n\nRem delectus eaque soluta. Temporibus nam aspernatur molestiae. Quidem veniam aut praesentium quo dignissimos voluptas. Quo nostrum voluptas pariatur est.\n\nFuga facilis esse corrupti dolores cum. Eos adipisci fuga et in et. Excepturi molestias rerum et dolorem nam corrupti.\n\nHarum maiores et iure. Nisi repellendus id ipsam quos consequatur sunt. Nihil impedit eum nemo aperiam numquam cupiditate. Qui molestiae cupiditate voluptatibus omnis ut.\n\nEst enim tempore dolore officia. Voluptas rerum maiores laboriosam voluptatem. Eos nihil qui sint consequuntur nulla. Adipisci rerum vel asperiores dolores.\n\nIure delectus quia facere quis rerum et. Dolores ut at aut rerum ut autem aut. Doloribus incidunt rerum molestiae sint iusto et accusamus sint. Qui aspernatur sint saepe placeat rerum animi aliquam.\n\nQuos distinctio eum distinctio ex nihil. Suscipit nesciunt adipisci mollitia corporis. Quis ex aut voluptas voluptatum. Ea et delectus cum. Qui aut voluptatem dolorem eos nihil.', 'Nesciunt voluptatibus iusto provident quidem tempora maxime voluptatem. Sed repellat sint est non est. Vel iure doloremque ut. Ducimus ipsa non sed doloremque necessitatibus.', 'Est fugiat ab pariatur fuga.', 'dolor,consectetur,aliquam', NULL, '2021-10-13 08:51:52', '2021-10-13 08:51:52'),
	(23, 'Et quae ratione iusto aut.', '1993-02-22', '/storage/téléchargement2.jpeg', 'Doloremque neque est fugit qui minima excepturi sunt. Fuga labore voluptas similique rerum ea non ut. Occaecati aut voluptas in vel eligendi odit consequatur voluptatem.\n\nEst libero dolorem autem rerum quod fugit. Accusamus ut aut reiciendis. Et consequatur eos veritatis assumenda. Nobis mollitia vero rerum ut exercitationem.\n\nEst maiores odio veniam at eum unde. Qui vel quibusdam enim cumque quia. Enim et rerum in explicabo reprehenderit voluptate et. Dolor aperiam dolorem illum voluptates quae cupiditate itaque.\n\nExplicabo et dolores velit nemo et. Nam perferendis voluptatum ut consequatur. Optio quod rerum non non omnis dolorem.\n\nNon nihil ratione at earum nesciunt. Architecto quis ullam et ullam molestiae impedit et. Iste molestias possimus et temporibus nesciunt possimus. Ut consequuntur ullam distinctio aut dolores sed.\n\nEos dolor enim voluptatem itaque et nobis officia. Ducimus aperiam quis beatae. Dolorem voluptas quia asperiores alias adipisci natus et. Similique unde veniam mollitia voluptatibus eum voluptatem.\n\nFugit ut nostrum ullam voluptatem deleniti necessitatibus quod repellendus. Rerum vel quia corporis esse quasi. Fugit non eius quia doloremque. Aliquid et reprehenderit ad minus officia consequuntur.\n\nVeritatis quos excepturi soluta nemo sit et officiis omnis. Consectetur a hic doloribus molestias et ut. Tempora aliquid illum voluptatem animi. Voluptate recusandae saepe necessitatibus qui voluptate velit. Sunt impedit voluptas aut ipsa officia error non porro.', 'Sed delectus sunt quo molestiae odit suscipit. Aspernatur ut sint omnis aut. Nihil mollitia deleniti quidem placeat voluptatem explicabo consequatur nihil. Fuga quis vel sed quia.', 'Et quas nobis molestiae laborum.', 'suscipit,ad,accusamus', NULL, '2021-10-13 08:51:52', '2021-10-13 08:51:52'),
	(24, 'Cum enim eaque id non.', '1980-06-14', '/storage/téléchargement3.jpeg', 'Nihil voluptatem facere commodi dicta non doloremque fugiat. Et aliquid sed adipisci quae pariatur corrupti nesciunt. Quo aliquid sint quas. Qui atque sint iure.\n\nQui aspernatur velit ut nulla. At accusamus quam aperiam aliquam. Sunt et soluta non blanditiis qui commodi fuga. Nisi est sed sit autem et sit.\n\nExplicabo minus tempora eum quia tempora error. Ex consequatur expedita magnam et voluptate. Voluptatem dolorum consequatur reprehenderit in.\n\nVoluptate et quod enim error. Quia accusamus assumenda ex vitae dicta molestiae. Illum dolor laboriosam sequi.\n\nTempora soluta sunt mollitia enim. Illo assumenda facilis assumenda alias corrupti. Et consectetur modi et molestiae magnam repellat est. Veritatis at similique corporis modi cupiditate consequatur. Voluptatem qui iure doloremque quam quae neque.\n\nDicta possimus modi dolorem vero et libero. Et rerum sunt tenetur quis ipsam perferendis ex quasi. Voluptatem consectetur id voluptatum nam. Fuga incidunt quia et perspiciatis eius.\n\nNatus quasi et ipsum qui quam dolorum fugiat. Dolores hic eos possimus cumque doloribus quis nemo. Facilis occaecati deleniti laborum et. Cupiditate accusamus accusantium sit consequatur voluptatem quibusdam.\n\nEt alias quasi et est voluptatem ducimus amet. Distinctio incidunt eos non aut nam impedit ut. Perspiciatis aliquid ratione sint consequatur.', 'Enim sit vitae consequatur vero officia. Quo voluptas odio suscipit harum et corrupti perferendis. Expedita vitae iure voluptatem tenetur.', 'Consequatur corporis illo voluptatem repellendus laborum aut magnam dicta.', 'non,reiciendis,non', NULL, '2021-10-13 08:51:52', '2021-10-13 08:51:52'),
	(25, 'Suscipit quis ipsum cupiditate dolorum.', '2000-07-28', '/storage/téléchargement1.jpeg', 'Occaecati ducimus molestiae voluptatibus tenetur in minima. Inventore ducimus officia hic architecto adipisci velit. Consectetur ad fuga autem voluptas autem doloribus.\n\nDeserunt aut ea natus incidunt neque omnis aut. Officiis voluptatem ad vitae ut aut.\n\nAut voluptatibus occaecati eos ut praesentium assumenda. Quia minus est ipsam suscipit. Vitae facere cum laborum necessitatibus sit earum.\n\nQuia rerum veniam tempora sed sed perspiciatis dolor doloribus. Sed illo beatae blanditiis distinctio.\n\nAutem dolores consequatur enim aut. Deleniti dolorem temporibus dolorem. Dolores animi in et adipisci eaque a reprehenderit.\n\nAut quo nostrum dolores id asperiores nobis. Molestiae impedit quia aut quis. Quia nisi perspiciatis iure corporis pariatur ut consequatur occaecati. Dicta voluptates est magni quisquam.\n\nFacilis exercitationem qui vel aliquid. Qui natus optio sit non iste recusandae vel. Laboriosam repudiandae cupiditate eligendi vitae in tempora. Explicabo sint voluptatum illum.\n\nNihil illum eaque animi nesciunt ipsam. Eum aut magnam illum alias. Eveniet aut laborum qui corrupti. Alias minima consequatur voluptatibus fugit illum saepe.', 'Culpa in alias facilis voluptatem voluptates sed. Repellendus suscipit necessitatibus esse possimus nihil qui nostrum. Id labore eos exercitationem fuga vel ducimus facilis.', 'Excepturi sint earum dolorum dolores cumque.', 'magni,et,veritatis', NULL, '2021-10-13 08:51:52', '2021-10-13 08:51:52'),
	(26, 'Quidem sequi ea magni qui.', '2005-06-30', '/storage/téléchargement2.jpeg', 'Quia molestiae incidunt assumenda tenetur aut. Voluptate aperiam reprehenderit in quaerat minima eligendi. Fugiat veniam eos veritatis provident. Deleniti quibusdam ipsam sint quia ad dolore.\n\nSequi numquam non sit quos ipsa aperiam. Reprehenderit harum commodi amet. Sed ad quaerat ratione quam accusantium enim.\n\nQuo et accusamus explicabo et. Sunt ipsa voluptatem facere ea. Eaque corrupti officia voluptatem quibusdam illo. Aut veritatis possimus eum quaerat recusandae.\n\nDeleniti nulla cupiditate qui perferendis. Nulla occaecati ipsa ex deserunt. Est beatae minima dolor quidem dolore. Exercitationem amet quis quia facere repudiandae.\n\nDolorum dolore qui enim fuga vel. Quia totam dolorum odit dicta culpa. Cupiditate excepturi eos porro inventore. Est ratione deleniti odit voluptas rem.\n\nNon enim cumque magni voluptas nesciunt esse. Repellat fugit qui voluptatum qui velit et nemo. Qui eum earum corrupti commodi et. Quo veritatis non numquam culpa aliquid sit.\n\nOdio molestiae et sint hic maxime. Illo sed quidem aliquam adipisci voluptas sed. Qui rerum dolore aperiam sint ut aut recusandae. Aut minima natus necessitatibus animi voluptatem sit facere.\n\nAut est maiores reiciendis. Exercitationem et illum qui nesciunt officia. Est amet reprehenderit rem rem vel maxime odio. Debitis et in voluptatem quo ut.', 'Voluptate tempore modi omnis omnis hic et. Est inventore enim odio et. Dolores enim assumenda sequi et et repellat unde.', 'Sed qui delectus laboriosam cum repellat.', 'quia,laboriosam,illum', NULL, '2021-10-13 08:51:52', '2021-10-13 08:51:52'),
	(27, 'Vero non quia voluptatem dolor dolorem.', '2015-04-26', '/storage/téléchargement3.jpeg', 'Quo aut expedita non deleniti qui delectus doloremque perferendis. Accusantium ut eaque in tempora corporis inventore eum. Iure non ut explicabo qui non voluptatem non.\n\nMinima et iure quod nam autem. Aut et et architecto illum laudantium laudantium qui. Vel dolores aut eius iusto. Voluptates voluptatum dolorem totam tempore.\n\nDeleniti ullam sit beatae iure. Sint quasi alias iusto ipsa. Eum possimus quasi blanditiis.\n\nAlias et saepe quas ut voluptates aspernatur saepe. Similique aliquam facilis sed cumque. Asperiores quis provident facere nihil enim est. Culpa accusantium minima voluptatem qui eum voluptatem.\n\nMagnam ad iusto id sunt cumque. Sunt molestiae explicabo corrupti et corporis omnis. Ut facilis velit beatae mollitia sed sequi. Et necessitatibus numquam ipsa cupiditate et ipsam. Nesciunt quaerat recusandae aliquid.\n\nCorporis sunt velit a nulla. Assumenda commodi voluptas similique.\n\nDelectus dolorem laborum sed eos. Sunt eum aliquam enim earum. Voluptas velit dolores sapiente voluptas voluptatem. Accusamus quam omnis quibusdam dignissimos iure.\n\nNostrum quia provident dicta omnis nobis. Modi facilis ea modi voluptatem perspiciatis aliquid.', 'Iusto qui architecto aut rem. Saepe veniam aut consequatur recusandae minus. Distinctio ipsa voluptatem sint omnis non et. Inventore voluptatem non quibusdam.', 'Illo fuga dolorem ipsa aliquid facilis.', 'doloremque,quibusdam,et', NULL, '2021-10-13 08:51:52', '2021-10-13 08:51:52'),
	(28, 'Voluptatibus voluptatibus itaque amet.', '1987-07-21', '/storage/téléchargement1.jpeg', 'Sed quo et distinctio illum minima. Repudiandae ratione excepturi cupiditate et.\n\nAccusantium illum doloribus quibusdam beatae magni ratione. In et impedit qui nam id molestias. Neque assumenda vel voluptas est eligendi commodi iure fugiat. Quia et sit ipsa ut aut autem rem.\n\nDeleniti consequatur dolorem nesciunt est ut. Quam eum explicabo et quaerat fugiat quas at. Aperiam adipisci consequatur officia esse sunt sint.\n\nDignissimos aut voluptatem possimus aperiam. Adipisci delectus illum qui debitis. Qui placeat magnam perferendis in rerum.\n\nEst unde est architecto. Expedita quod et repellat qui rem voluptas et consequatur. Rem distinctio error perferendis quia minus enim.\n\nFuga quia perspiciatis qui dolores nulla asperiores dolorum. Laboriosam omnis dolore dolor tempora rerum. Similique quia facere culpa exercitationem voluptas.\n\nDistinctio et ratione ullam in nam in. Laboriosam dolore deserunt est consequatur ipsa tempore non. Odio quia voluptas enim nihil nobis veniam. Est incidunt quod fuga iste quis rerum nisi.\n\nEnim ut dolorem deserunt maiores. Qui laborum iste quia tempora. Officia repellendus dolore eaque exercitationem. Magnam sunt eos veniam labore molestiae ipsam beatae.', 'Aut quod est magnam explicabo id quae. Dolores consectetur consequatur consequatur saepe nostrum. A hic suscipit molestias atque sed ad.', 'Quos esse iste aut accusamus vel et.', 'voluptatem,nam,adipisci', NULL, '2021-10-13 08:51:52', '2021-10-13 08:51:52'),
	(29, 'Sed tempore officia molestiae dignissimos.', '2007-11-19', '/storage/téléchargement2.jpeg', 'Consequuntur debitis incidunt blanditiis est voluptatem quia debitis. Rem voluptate est ullam assumenda dolor sit et. Sint sint architecto eos nobis cumque ut autem. Consequatur in veritatis eos est qui. Assumenda alias sit asperiores.\n\nAutem nobis voluptas saepe. Odio doloribus placeat omnis optio doloremque voluptatem. Consequatur aut consectetur id aut dolor voluptate aut sequi.\n\nVel et sint quis harum qui quas eum. Voluptatem a et esse nihil officia veniam. Consequatur non reprehenderit quibusdam repudiandae minima vero. Ut occaecati excepturi illo cumque similique.\n\nAlias deleniti inventore aliquam minima exercitationem ullam. Omnis provident eaque ut consequatur ipsum doloremque non. Et ad cumque et consequatur.\n\nUllam commodi laudantium hic consequatur. Et non deserunt rerum. Explicabo quia quia magni ipsa. Ad voluptatibus occaecati corrupti nisi corrupti.\n\nReiciendis dolores cupiditate reiciendis consectetur ipsa aliquid eum. Eos optio vero alias est et sit dolor. Iusto consectetur perspiciatis nam. Eius quia explicabo magni veniam a excepturi.\n\nAut earum unde aut expedita minus laborum. In sed delectus similique. Nam id officiis enim. Cum quo quaerat distinctio soluta ut harum quo.\n\nCorrupti ducimus fugiat voluptatibus autem. Voluptas quasi sunt non. Pariatur esse enim quod necessitatibus ipsam corporis.', 'Est dolorem et non labore maxime omnis natus voluptatem. Quasi officiis qui culpa cupiditate odio. Voluptas ullam et delectus consequatur rerum ad et.', 'Beatae blanditiis quibusdam officiis omnis ex doloremque debitis.', 'omnis,ex,veniam', NULL, '2021-10-13 08:51:52', '2021-10-13 08:51:52'),
	(30, 'Pariatur consequatur aut dolor cum autem.', '1990-04-29', '/storage/téléchargement3.jpeg', 'Enim omnis quo ut nihil. Voluptatem dolores nostrum omnis. Impedit consectetur quia ipsum et vitae.\n\nIncidunt ad nam libero sit ducimus. Ducimus in ea pariatur ut. Occaecati nam numquam voluptate iure. Omnis dolores totam veniam neque. Quo reprehenderit beatae adipisci omnis ut.\n\nPerferendis laborum aut quo eveniet nam aut voluptate. Est dolorem labore occaecati nihil. Nihil dicta at dolorem sint placeat dolor tenetur.\n\nNatus dolorem nihil impedit. Sint modi inventore labore accusantium ea suscipit. Ut rem facilis explicabo qui dolorum neque est ea. Porro fugit occaecati nisi excepturi hic nihil corrupti.\n\nVel nesciunt ut magni et magni et. Eligendi cupiditate molestiae in distinctio dolores eveniet. Aut blanditiis dolor cumque.\n\nSit impedit labore rerum eum. Hic perferendis perspiciatis sequi quas aut tempore omnis odio. A in nesciunt necessitatibus distinctio dolor.\n\nVoluptate perferendis a aut enim. Ut quos et ut ut. Suscipit voluptatem rerum ratione reprehenderit delectus at. Quis temporibus expedita voluptates explicabo.\n\nOptio et facilis voluptas beatae. Ipsum nemo aut expedita placeat.', 'Eum nesciunt ut vero enim ea. Nobis et quos quaerat porro sit reiciendis id quo. Dolorem dolore quis sed officiis ipsa assumenda alias.', 'Ab iure ipsam natus veritatis porro consectetur.', 'iusto,nisi,minima', NULL, '2021-10-13 08:51:52', '2021-10-13 08:51:52');
/*!40000 ALTER TABLE `projects` ENABLE KEYS */;

-- Listage de la structure de la table portfolio_laravel. users
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Listage des données de la table portfolio_laravel.users : ~0 rows (environ)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
